Repository Johny1010/WDP-1905-01, pull requests merged in 2019-06, with the labels that each got.

#5 Wdp190501 6
  src/partials/50_section-products.html
  src/sass/components/_product-box.scss
Labels: ready to merge

#9 Wdp190501 12
  src/partials/10_header.html
  src/sass/components/_header.scss
Labels: ready to merge

#18 WDP19501-24
  src/index.html
  src/partials/40_section-promotion.html
  src/sass/components/_section--promotion.scss
  src/sass/style.scss
Labels: ready to merge

#8 WDP190501-8
  src/partials/70_section-blog-posts.html
  src/sass/components/_post-box.scss
Labels: ready to merge

#12 WDP190501-1
  src/images/post1.jpeg
  src/images/post2.jpeg
  src/images/post3.jpeg
  src/images/product1.jpeg
  src/images/product2.jpeg
  src/images/product3.jpeg
  src/images/product4.jpeg
  src/images/product5.jpeg
  src/images/product6.jpeg
  src/images/product7.jpeg
  src/images/product8.jpeg
  src/partials/50_section-products.html
  src/partials/70_section-blog-posts.html
  src/sass/components/_post-box.scss
  src/sass/components/_product-box.scss
Labels: ready to merge

#24 WDP190501-29
  src/index.html
  src/partials/80_section-brands.html
  src/sass/components/_section--brands.scss
  src/sass/style.scss
Labels: ready to review

#23 WDP-190501-20
  src/partials/40_section-promotion.html
  src/sass/components/_section--promotion.scss
Labels: ready to review

#15 WDP190501-15
  src/partials/70_section-blog-posts.html
Labels: ready to merge

#16 WDP-190501-20
  package-lock.json
  ppsadsadPP
  src/index.html
  src/partials/70_section-blog-posts.html
  src/sass/components/_footer.scss
  src/sass/components/_panel-bar.scss
  src/sass/components/_post-box.scss
  src/scripts/sliders.js
Labels: ready to review

#21 Wdp190501-32
  src/index.html
  src/partials/100_footer.html
  src/partials/90_section-feedback.html
  src/sass/components/_section--feedback.scss
  src/sass/style.scss
Labels: ready to merge

#20 WDP190501-21
  src/index.html
  src/partials/20_section-product-promotion.html
  src/partials/50_section-products.html
  src/partials/70_section-blog-posts.html
  src/sass/components/_product-box.scss
  src/sass/components/_section--product-promotion.scss
  src/sass/style.scss
Labels: conflicts
